// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZDALfTUKu_NJzCix1Cy4MWfZh7QyE3c',
    appId: '1:185150717388:web:71ec41febf76ac2f047169',
    messagingSenderId: '185150717388',
    projectId: 'medifyapp-16cd4',
    authDomain: 'medifyapp-16cd4.firebaseapp.com',
    storageBucket: 'medifyapp-16cd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWh8ZBFBbMgbqdBzmWe8K4dxJiZqCJ0X0',
    appId: '1:185150717388:android:5b819dbed7e138c9047169',
    messagingSenderId: '185150717388',
    projectId: 'medifyapp-16cd4',
    storageBucket: 'medifyapp-16cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucfOr94mgDqo6o68EUGckkU9MCdGfUoc',
    appId: '1:185150717388:ios:81cfc4587e8a78a5047169',
    messagingSenderId: '185150717388',
    projectId: 'medifyapp-16cd4',
    storageBucket: 'medifyapp-16cd4.firebasestorage.app',
    iosBundleId: 'com.alevega.medifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBucfOr94mgDqo6o68EUGckkU9MCdGfUoc',
    appId: '1:185150717388:ios:81cfc4587e8a78a5047169',
    messagingSenderId: '185150717388',
    projectId: 'medifyapp-16cd4',
    storageBucket: 'medifyapp-16cd4.firebasestorage.app',
    iosBundleId: 'com.alevega.medifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ZDALfTUKu_NJzCix1Cy4MWfZh7QyE3c',
    appId: '1:185150717388:web:9e1785ff20bd9039047169',
    messagingSenderId: '185150717388',
    projectId: 'medifyapp-16cd4',
    authDomain: 'medifyapp-16cd4.firebaseapp.com',
    storageBucket: 'medifyapp-16cd4.firebasestorage.app',
  );
}
